SmartGarage/SmartGarage/Controllers/ManufacturerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SmartGarage.Data;
using SmartGarage.Data.Models;
using SmartGarage.Service.Contracts;
using SmartGarage.Service.DTOs.GetDTOs;
using SmartGarage.Service.DTOs.Shared;
using SmartGarage.Service.Helpers;
using System.Threading.Tasks;

namespace SmartGarage.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    [Authorize]
    public class ManufacturerController : Controller
    {
        private readonly IManufacturerService service;

        public ManufacturerController(IManufacturerService service)
        {
            this.service = service;
        }

        public SmartGarageContext Context { get; }

        // GET: Manufacturers
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Index()
        {
            int pageNumber = 1;
            var pageSize = 8;
            var manufacturers = await service.GetAll();

            return View(PaginatedList<GetManufacturerDTO>.CreateAsync(manufacturers, pageNumber, pageSize));
        }

        [Authorize(Roles = "Admin,Employee")]
        [HttpGet("Manufacturer/Get")]
        public async Task<IActionResult> IndexPartial(int pageNumber)
        {
            var pageSize = 8;
            var manufacturers = await service.GetAll();

            return PartialView("Manufacturer_Table_Partial", PaginatedList<GetManufacturerDTO>.CreateAsync(manufacturers, pageNumber, pageSize));
        }
        //GET: Manufacturers/Details/5       
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Details(int id)
        {
            var manufacturer = await service.GetAsync(id);

            if (manufacturer == null)
            {
                return NotFound();
            }

            return View(manufacturer);
        }

        //GET: Manufacturers/Edit/5     
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Edit(int id)
        {
            var manufacturer = await service.GetAsync(id);

            if (manufacturer == null)
            {
                return NotFound();
            }

            return View(manufacturer);
        }

        //POST: Manufacturers/Edit/5   
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Edit(int id, Manufacturer manufacturer)
        {
            if (id != manufacturer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var updateInformaniton = new ManufacturerDTO
                {
                    Name = manufacturer.Name
                };

                await service.UpdateAsync(updateInformaniton, id);
                return RedirectToAction(nameof(Index));
            }

            return View(manufacturer);
        }

        // GET: Manufacturers/Create
        [Authorize(Roles = "Admin,Employee")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Manufcaturers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Create(ManufacturerDTO manufacturer)
        {
            if (ModelState.IsValid)
            {
                await service.CreateAsync(manufacturer);
                return RedirectToAction(nameof(Index));
            }

            return View(manufacturer);
        }
    }
}

SmartGarage/SmartGarage/Controllers/VehicleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SmartGarage.Data.Models;
using SmartGarage.Service.Contracts;
using SmartGarage.Service.DTOs.CreateDTOs;
using SmartGarage.Service.DTOs.GetDTOs;
using SmartGarage.Service.DTOs.UpdateDTOs;
using SmartGarage.Service.Helpers;
using SmartGarage.Service.ServiceContracts;
using SmartGarage.ViewModels;
using System.Linq;
using System.Threading.Tasks;

namespace SmartGarage.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    [Authorize]
    public class VehicleController : Controller
    {
        private readonly IVehicleService service;
        private readonly IManufacturerService manufacturerService;
        private readonly IVehicleModelService vehicleModelService;
        private readonly UserManager<User> userManager;

        public VehicleController(IVehicleService service,
            IManufacturerService manufacturerService,
            IVehicleModelService vehicleModelService,
            UserManager<User> userManager)
        {
            this.service = service;
            this.manufacturerService = manufacturerService;
            this.vehicleModelService = vehicleModelService;
            this.userManager = userManager;
        }

        [Authorize(Roles = "Admin,Employee,Customer")]
        public async Task<IActionResult> Index()
        {
            var user = await userManager.FindByNameAsync(User.Identity.Name);

            int pageNumber = 1;
            string name = default;
            var pageSize = 8;
            var vehicles = await service.GetAll(name);

            if (user.CurrentRole == "CUSTOMER")
            {
                vehicles = vehicles.Where(v => v.UserId == user.Id).ToList();

                return View(PaginatedList<GetVehicleDTO>.CreateAsync(vehicles, pageNumber, pageSize));
            }
            return View(PaginatedList<GetVehicleDTO>.CreateAsync(await service.GetAll(name), pageNumber, pageSize));
        }

        [HttpGet("Vehicle/Filter")]
        [Authorize(Roles = "Admin,Employee,Customer")]
        public async Task<IActionResult> PartialView(string name, int pageNumber = 1)
        {
            var pageSize = 8;
            return PartialView("Vehicle_Table_Partial", PaginatedList<GetVehicleDTO>.CreateAsync(await service.GetAll(name), pageNumber, pageSize));
        }

        // GET: Vehicles/Details/5
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Details(int id)
        {
            var vehicle = await service.GetAsync(id);

            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // GET: Vehicles/Details/5
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Edit(int id)
        {
            var vehicle = await service.GetAsync(id);

            if (vehicle == null)
            {
                return NotFound();
            }

            var vehicleToUpdate = new VehicleViewModel
            {
                Id = vehicle.Id,
                VehicleModelId = vehicle.VehicleModelId,
                VIN = vehicle.VIN,
                NumberPlate = vehicle.NumberPlate,
                Colour = vehicle.Colour,
                Manufacturers = await manufacturerService.GetAll(),
                Models = await vehicleModelService.GetAll()
            };

            return View(vehicleToUpdate);
        }

        // POST: Vehicles/Details/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Edit(int id, VehicleViewModel updateInformation)
        {
            var vehicleInformation = new UpdateVehicleDTO
            {
                NumberPlate = updateInformation.NumberPlate,
                Colour = updateInformation.Colour
            };

            try
            {
                await service.UpdateAsync(vehicleInformation, id);
                return RedirectToAction(nameof(Index));
            }
            catch (System.Exception)
            {
                return RedirectToAction("Edit", "VehicleModel");
            }
        }

        // GET: Vehicles/Create
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Create()
        {
            var model = new VehicleViewModel
            {
                Manufacturers = await manufacturerService.GetAll(),
                Models = await vehicleModelService.GetAll()
            };

            return View(model);
        }

        // POST: Vehicles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Create(VehicleViewModel vehicle, int id)
        {
            if (vehicle.ManufacturerId == default || vehicle.VehicleModelId == default)
            {
                TempData["Error"] = "Please select existing manufacturer and vehicle model.";
                return RedirectToAction("Index","User");
            }

            var createVehicle = new CreateVehicleDTO
            {
                UserId = id,
                NumberPlate = vehicle.NumberPlate,
                Colour = vehicle.Colour,
                VehicleModelId = vehicle.VehicleModelId,
                VIN = vehicle.VIN
            };

            await service.CreateAsync(createVehicle);
            return RedirectToAction(nameof(Index));
        }

        // GET: Vehicles/Delete/5
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Delete(int id)
        {
            var vehicleToRemove = await service.GetAsync(id);

            if (vehicleToRemove == null)
            {
                return NotFound();
            }

            return View(vehicleToRemove);
        }

        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await service.RemoveAsync(id);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> VehicleModels(int? id)
        {
            var models = await vehicleModelService.GetAll();

            return Json(models.Where(x => x.ManufacturerId == id).ToList());
        }
    }
}

SmartGarage/SmartGarage/Views/Shared/Manufacturer_Table_Partial.cshtml
@model PaginatedList<GetManufacturerDTO>

<table class="table table-dark table-hover text-white">
    <thead>
        <tr style="line-height: 37px;">
            <th>
                <p class="m-0">#</p>
            </th>
            <th>
                <p class="m-0">Name</p>
            </th>
            <th style="width:170px">
            </th>
        </tr>
    </thead>
    <tbody>
        @{
            int count = 1 + (Model.PageIndex - 1) * Model.PageSize;

            foreach (var item in Model.ItemsCollection)
            {
                if (count % 2 != 0)
                {
                    <tr class="table-active" style="line-height: 37px;">
                        <th scope="row">
                            @count
                        </th>
                        <td>@Html.DisplayFor(modelItem => item.Name)</td>
                        <td>
                            <a onclick="showInPopup('@Url.Action("Edit","Manufacturer",new {id = item.Id }, Context.Request.Scheme)', 'Update Manufacturer')" class="btn btn-outline-warning text-white">Edit</a>
                            <a onclick="showInPopup('@Url.Action("Details","Manufacturer",new {id = item.Id }, Context.Request.Scheme)', 'Manufacturer')" class="btn btn-outline-info text-white">Details</a>
                        </td>
                    </tr>
                }
                else
                {
                    <tr style="line-height: 37px;">
                        <th scope="row">
                            @count
                        </th>
                        <td>@Html.DisplayFor(modelItem => item.Name)</td>
                        <td>
                            <a onclick="showInPopup('@Url.Action("Edit","Manufacturer",new {id = item.Id }, Context.Request.Scheme)', 'Update Manufacturer')" class="btn btn-outline-warning text-white">Edit</a>
                            <a onclick="showInPopup('@Url.Action("Details","Manufacturer",new {id = item.Id }, Context.Request.Scheme)', 'Manufacturer')" class="btn btn-outline-info text-white">Details</a>
                        </td>
                    </tr>
                }
                count++;
            }
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<nav aria-label="...">
    <ul class="pagination">
        @if (Model.PageIndex > 4 && Model.PageIndex + 3 < Model.TotalPages)
        {
            <li class="page-item disabled">
                <a href="#" class="btn btn-outline-success text-white @prevDisabled" id="prev">Previous</a>
            </li>
            <li class="page-item">
                <a class="btn btn-outline-success text-white" href="#">1</a>
            </li>
            <li class="page-item">
                <a class="btn btn-outline-success text-white" href="#!">...</a>
            </li>
            <li class="page-item">
                <a class="btn btn-outline-success text-whitek" href="#">@(Model.PageIndex-1)</a>
            </li>
            <li class="page-item">
                <a class="btn btn-outline-success text-white active" href="#">@Model.PageIndex</a>
            </li>
            <li class="page-item">
                <a class="btn btn-outline-success text-white" href="#">@(Model.PageIndex+1)</a>
            </li>
            <li class="page-item">
                <a class="btn btn-outline-success text-white" href="#!">...</a>
            </li>
            <li class="btn btn-outline-success text-white">
                <a class="btn btn-outline-success text-white" href="#">@Model.TotalPages</a>
            </li>
            <li class="btn btn-outline-success text-white">
                <a href="#" class="btn btn-outline-success text-white @nextDisabled" id="next">Next</a>
            </li>

        }
        else if (Model.PageIndex > 4 && Model.PageIndex + 3 >= Model.TotalPages)
        {
            <li class="page-item disabled">
                <a href="#" class="btn btn-outline-success text-white @prevDisabled" id="prev">Previous</a>
            </li>
            <li class="page-item">
                <a class="btn btn-outline-success text-white" href="#">1</a>
            </li>
            <li class="page-item">
                <a class="btn btn-outline-success text-white" href="#!">...</a>
            </li>
            @for (int i = Model.TotalPages - 3; i <= Model.TotalPages; i++)
            {
                @if (Model.PageIndex == i)
                {
                    <li class="page-item">
                        <a class="btn btn-outline-success text-white active" href="#">@i</a>
                    </li>
                }
                else
                {
                    <li class="page-item">
                        <a class="btn btn-outline-success text-white" href="#">@i</a>
                    </li>
                }
            }
            <li class="page-item">
                <a href="#" class="btn btn-outline-success text-white @nextDisabled" id="next">Next</a>
            </li>
        }
        else if (Model.TotalPages > 4 && Model.PageIndex < 5)
        {
            <li class="page-item disabled">
                <a href="#" class="btn btn-outline-success text-white @prevDisabled" id="prev">Previous</a>
            </li>
            @for (int i = 1; i <= 4; i++)
            {
                @if (Model.PageIndex == i)
                {
                    <li class="page-item">
                        <a class="btn btn-outline-success text-white active" href="#">@i</a>
                    </li>
                }
                else
                {
                    <li class="page-item">
                        <a class="btn btn-outline-success text-white" href="#">@i</a>
                    </li>
                }
            }
            <li class="page-item">
                <a class="btn btn-outline-success text-white" href="#!">...</a>
            </li>
            <li>
                <a class="btn btn-outline-success text-white" href="#">@Model.TotalPages</a>
            </li>
            <li class="page-item">
                <a href="#" class="btn btn-outline-success text-white @nextDisabled" id="next">Next</a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a href="#" class="btn btn-outline-success text-white @prevDisabled" id="prev">Previous</a>
            </li>
            @for (int i = 1; i <= Model.TotalPages; i++)
            {
                @if (Model.PageIndex == i)
                {
                    <li class="page-item">
                        <a href="#" class="btn btn-outline-success text-white active">@i</a>
                    </li>
                }
                else
                {
                    <li class="page-item">
                        <a href="#" class="btn btn-outline-success text-white">@i</a>
                    </li>
                }
            }
            <li class="page-item">
                <a href="#" class="btn btn-outline-success text-white @nextDisabled" id="next">Next</a>
            </li>
        }
    </ul>
</nav>
<input hidden id="page" value="@Model.PageIndex" />

SmartGarage/SmartGarage/Views/Shared/ServiceCustomer_Table_Partial.cshtml
@model PaginatedList<GetServiceDTO>

<table class="table table-dark table-hover">
    <thead>
        <tr style="line-height: 37px;">
            <th style="width:103.55px;">
                <p class="m-0">#</p>
            </th>
            <th>
                <p class="m-0">Name</p>
            </th>
            <th>
                <p class="m-0">Price</p>
            </th>
        </tr>
    </thead>
    <tbody>
        @{
            int count = 1 + (Model.PageIndex - 1) * Model.PageSize;

            foreach (var item in Model.ItemsCollection)
            {
                if (count % 2 != 0)
                {
                    <tr style="line-height: 37px;" class="table-active">
                        <th scope="row">
                            @count
                        </th>
                        <td style="width:369.11px;">@Html.DisplayFor(modelItem => item.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.Price)<b class="ml-1" style="font-size:10px;">EUR</b></td>
                    </tr>
                }
                else
                {
                    <tr style="line-height: 37px;">
                        <th scope="row">
                            @count
                        </th>
                        <td style="width:369.11px;">@Html.DisplayFor(modelItem => item.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.Price)<b class="ml-1" style="font-size:10px;">EUR</b></td>

                    </tr>
                }
                count++;
            }
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<nav aria-label="...">
    <ul class="pagination">
        @if (Model.PageIndex > 4 && Model.PageIndex + 3 < Model.TotalPages)
        {
            <li class="page-item disabled">
                <a href="#" class="btn btn-outline-success text-white @prevDisabled" id="prev">Previous</a>
            </li>
            <li class="page-item">
                <a class="btn btn-outline-success text-white" href="#">1</a>
            </li>
            <li class="page-item">
                <a class="btn btn-outline-success text-white" href="#!">...</a>
            </li>
            <li class="page-item">
                <a class="btn btn-outline-success text-whitek" href="#">@(Model.PageIndex-1)</a>
            </li>
            <li class="page-item">
                <a class="btn btn-outline-success text-white active" href="#">@Model.PageIndex</a>
            </li>
            <li class="page-item">
                <a class="btn btn-outline-success text-white" href="#">@(Model.PageIndex+1)</a>
            </li>
            <li class="page-item">
                <a class="btn btn-outline-success text-white" href="#!">...</a>
            </li>
            <li class="btn btn-outline-success text-white">
                <a class="btn btn-outline-success text-white" href="#">@Model.TotalPages</a>
            </li>
            <li class="btn btn-outline-success text-white">
                <a href="#" class="btn btn-outline-success text-white @nextDisabled" id="next">Next</a>
            </li>

        }
        else if (Model.PageIndex > 4 && Model.PageIndex + 3 >= Model.TotalPages)
        {
            <li class="page-item disabled">
                <a href="#" class="btn btn-outline-success text-white @prevDisabled" id="prev">Previous</a>
            </li>
            <li class="page-item">
                <a class="btn btn-outline-success text-white" href="#">1</a>
            </li>
            <li class="page-item">
                <a class="btn btn-outline-success text-white" href="#!">...</a>
            </li>
            @for (int i = Model.TotalPages - 3; i <= Model.TotalPages; i++)
            {
                @if (Model.PageIndex == i)
                {
                    <li class="page-item">
                        <a class="btn btn-outline-success text-white active" href="#">@i</a>
                    </li>
                }
                else
                {
                    <li class="page-item">
                        <a class="btn btn-outline-success text-white" href="#">@i</a>
                    </li>
                }
            }
            <li class="page-item">
                <a href="#" class="btn btn-outline-success text-white @nextDisabled" id="next">Next</a>
            </li>
        }
        else if (Model.TotalPages > 4 && Model.PageIndex < 5)
        {
            <li class="page-item disabled">
                <a href="#" class="btn btn-outline-success text-white @prevDisabled" id="prev">Previous</a>
            </li>
            @for (int i = 1; i <= 4; i++)
            {
                @if (Model.PageIndex == i)
                {
                    <li class="page-item">
                        <a class="btn btn-outline-success text-white active" href="#">@i</a>
                    </li>
                }
                else
                {
                    <li class="page-item">
                        <a class="btn btn-outline-success text-white" href="#">@i</a>
                    </li>
                }
            }
            <li class="page-item">
                <a class="btn btn-outline-success text-white" href="#!">...</a>
            </li>
            <li>
                <a class="btn btn-outline-success text-white" href="#">@Model.TotalPages</a>
            </li>
            <li class="page-item">
                <a href="#" class="btn btn-outline-success text-white @nextDisabled" id="next">Next</a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a href="#" class="btn btn-outline-success text-white @prevDisabled" id="prev">Previous</a>
            </li>
            @for (int i = 1; i <= Model.TotalPages; i++)
            {
                @if (Model.PageIndex == i)
                {
                    <li class="page-item">
                        <a href="#" class="btn btn-outline-success text-white active">@i</a>
                    </li>
                }
                else
                {
                    <li class="page-item">
                        <a href="#" class="btn btn-outline-success text-white">@i</a>
                    </li>
                }
            }
            <li class="page-item">
                <a href="#" class="btn btn-outline-success text-white @nextDisabled" id="next">Next</a>
            </li>
        }
    </ul>
</nav>
<input hidden id="page" value="@Model.PageIndex" />

SmartGarage/SmartGarage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SmartGarage</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital@1&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        body {
            background-image: url('/images/Vehicles.jpg');
        }
    </style>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow">
            <div class="container">
                <a asp-controller="Home" asp-action="Index"> <img src="https://i.ibb.co/2gc4BKN/Better-Logo.png" alt="Better-Logo" border="0"></a>
                <button class="navbar-toggler flex-grow-1" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <p><partial name="_LoginPartial" /></p>
                    <ul class="navbar-nav flex-grow-1 justify-content-center">
                        @if (User.IsInRole("Employee") || User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Manufacturer"
                                   asp-action="Index">Manufacturers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link link text-white" asp-area="" asp-controller="VehicleModel"
                                   asp-action="Index">VehicleModels</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white " data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Customer</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item w-auto" asp-controller="User"
                                       asp-action="Index">All Customers</a>
                                    <a class="dropdown-item w-auto" asp-area="Identity" asp-page="/Account/ForgotPassword">Forgoten Password</a>
                                    <a class="dropdown-item w-auto" onclick="showInPopup('Identity/Account/Register','Register user')">Register User</a>
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <a class="dropdown-item w-auto" asp-controller="User"
                                           asp-action="UpdateAdmin">Update Role</a>
                                    }
                                </div>
                            </li>
                        }
                        @if (User.IsInRole("Employee") || User.IsInRole("Admin") || User.IsInRole("Customer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link link text-white" asp-area="" asp-controller="Vehicle"
                                   asp-action="Index">Vehicles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link link text-white" asp-area="" asp-controller="Order"
                                   asp-action="Index">Order </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link link text-white" asp-area="" asp-controller="Service"
                                   asp-action="Index">Services </a>
                            </li>
                            @if (User.IsInRole("Customer"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link link text-white" asp-area="Identity" asp-page="/Account/ChangePassword">Reset Password</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid p-0 m-0">
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <div class="modal" tabindex="-1" role="dialog" id="form-modal">
        <div class="modal-dialog modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header" style="background-color:#E8E8E8;">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
                    <span aria-hidden="true">&times;</span>
                </div>
                <div class="modal-body p-0 mt-0" style="background-color:#E8E8E8;">
                </div>
            </div>
        </div>
    </div>
    <footer class="border-top pt-0 footer text-muted bg-dark">
        <div class="container">
            &copy; 2021 - SmartGarage - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SmartGarage/SmartGarage/Views/Shared/_LayoutForPopup.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SmartGarage</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital@1&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container-fluid p-0 m-0">
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>